import * as Arrays from './arrays';
import * as Booleans from './boolean';
import * as CharCodes from './charCode';
import * as Errors from './error';
import * as Functional from './functional';
import * as Logger from './logger';
import * as Logical from './logical';
import * as Maths from './math';
import * as Range from './range';
import * as Relations from './relations';
import * as Strings from './strings';
import * as Typings from './typings';

export const BaseArray = Arrays;
export const BaseBoolean = Booleans;
export const BaseCharCodes = CharCodes;
export const BaseErrors = Errors;
export const BaseFunctional = Functional;
export const BaseLogger = Logger;
export const BaseLogical = Logical;
export const BaseMaths = Maths;
export const BaseRange = Range;
export const BaseRelations = Relations;
export const BaseStrings = Strings;
export const BaseTypings = Typings;
